### ISSUE TITLE
Not able to load OOF

### ISSUE THREAD

**Issue by keeyu2** [EvanBasalik/OOFSponder#30]
I have .Net 4.8 installed and when I try to launch OOF nothing happens.  It looks like something is blocking it. I excluded it from AntiVirus still not able to load.

**Comment by EvanBasalik** [comment]
It will be marked as from the internet, so depending on your local policies it might need to be allowed first. Check out https://www.msftnext.com/how-to-unblock-files-downloaded-from-internet-in-windows-10/.

**Comment by keeyu2** [comment]
There isn't a setting to mark it.
![oof](https://user-images.githubusercontent.com/16942707/110802440-d0a7a700-8243-11eb-9438-80e4aba61211.PNG)

I ran procmon and the last thing was load image from C:\windows\syswow64\combase.dll.  There were no access denied.

**Comment by keeyu2** [comment]
Following errors were detected during this operation.
	* [3/11/2021 8:41:03 AM] System.Runtime.InteropServices.COMException
		- The requested operation requires elevation. (Exception from HRESULT: 0x800702E4)
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.NativeMethods.CorLaunchApplication(UInt32 hostType, String applicationFullName, Int32 manifestPathsCount, String[] manifestPaths, Int32 activationDataCount, String[] activationData, PROCESS_INFORMATION processInformation)
			at System.Deployment.Application.ComponentStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.SubscriptionStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.ApplicationActivator.Activate(DefinitionAppId appId, AssemblyManifest appManifest, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.ApplicationActivator.ProcessOrFollowShortcut(String shortcutFile, String& errorPageUrl, TempFile& deployFile)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

**Comment by EvanBasalik** [comment]
Do you have admin rights on the machine where you are trying to install this?

**Comment by keeyu2** [comment]
I do which is odd that i am getting this message.

**Comment by abarqawi** [comment]
Hi @keeyu2  i have similar issue how did you solve it ?
